### ISSUE TITLE
Problem installing directly from GH

### ISSUE THREAD

**Issue by dokterbob** [Nytramr/npm-zepto#2]
Due to an [issue with NPM](https://github.com/npm/npm/issues/1876), the Zepto module is not checked out when installing straight from GitHub. This yields problems mainly when forking your repository as Zepto is not available in that case (i.e. when doing custom builds of Zepto).

As a workaround, I created a [Zepto fork](https://github.com/visualspace/npm-zepto-fork) combining your work with the original Zepto repository such that the contents of the Zepto repository are merged into the `zepto` folder (this should enable merging future updates to Zepto as well). Furthermore, I forked this work from Zepto 1.1.6.

I'm posting this issue mainly to alert other users who run into the same issue, to save them an afternoon of bothersome debugging and tinkering.

**Comment by mrubinsztein** [comment]
In order to use npm-zepto downloading it from github, the user must run `git submodule update` to download the Zepto submodule.

I will include this and other instructions to compile a custom Zepto version in the README file during this week.

Thanks.

**Comment by Nytramr** [comment]
Solve in commit 1f5e0516b9f9183cc10c22764fb9eb93d5210163
